In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import KernelDensity
import cartopy.crs as ccrs
import numpy as np
import scipy.stats as sts
from sqlalchemy import create_engine

In [2]:
#NBA_Games_Data path files

games_csv_path = "NBA_Games_Data/games.csv"
games_details_csv_path = "NBA_Games_Data/games_details.csv"
players_csv_path = "NBA_Games_Data/players.csv"
ranking_csv_path = "NBA_Games_Data/ranking.csv"
teams_csv_path = "NBA_Games_Data/teams.csv"

#march-machine-learning-mania-2017 path files

RegularSeasonCompactResults_csv_path = "march-machine-learning-mania-2017/RegularSeasonCompactResults.csv"
RegularSeasonDetailedResults_csv_path = "march-machine-learning-mania-2017/RegularSeasonDetailedResults.csv"
SampleSubmission_csv_path = "march-machine-learning-mania-2017/SampleSubmission.csv"
Seasons_csv_path = "march-machine-learning-mania-2017/Seasons.csv"
Teams_csv_path = "march-machine-learning-mania-2017/Teams.csv"
TourneyCompactResults_csv_path = "march-machine-learning-mania-2017/TourneyCompactResults.csv"
TourneyDetailedResults_csv_path = "march-machine-learning-mania-2017/TourneyDetailedResults.csv"

In [3]:
#NBA_Games_Data data frames

games_df = pd.read_csv(games_csv_path, delimiter = ',', lineterminator='\n')
games_details_df = pd.read_csv(games_details_csv_path, delimiter = ',', lineterminator='\n')
players_df = pd.read_csv(players_csv_path, delimiter = ',', lineterminator='\n')
ranking_df = pd.read_csv(ranking_csv_path, delimiter = ',', lineterminator='\n')
teams_df = pd.read_csv(teams_csv_path, delimiter = ',', lineterminator='\n')

#march-machine-learning-mania-2017 data frames

RegularSeasonCompactResults_df = pd.read_csv(RegularSeasonCompactResults_csv_path, delimiter = ',', lineterminator='\n')
RegularSeasonDetailedResults_df = pd.read_csv(RegularSeasonDetailedResults_csv_path, delimiter = ',', lineterminator='\n')
SampleSubmission_df = pd.read_csv(SampleSubmission_csv_path, delimiter = ',', lineterminator='\n')
Seasons_df = pd.read_csv(Seasons_csv_path, delimiter = ',', lineterminator='\n')
Teams_df = pd.read_csv(Teams_csv_path, delimiter = ',', lineterminator='\n')
TourneyCompactResults_df = pd.read_csv(TourneyCompactResults_csv_path, delimiter = ',', lineterminator='\n')
TourneyDetailedResults_df = pd.read_csv(TourneyDetailedResults_csv_path, delimiter = ',', lineterminator='\n')

In [4]:
ranking_df.head()

,TEAM_ID,LEAGUE_ID,SEASON_ID,STANDINGSDATE,CONFERENCE,TEAM,G,W,L,W_PCT,HOME_RECORD,ROAD_RECORD,RETURNTOPLAY
0,1610612747,0,12020,2020-12-21,West,L.A. Lakers,4,4,0,1.00,2-0,2-0,NaN
1,1610612762,0,12020,2020-12-21,West,Utah,3,3,0,1.00,2-0,1-0,NaN
2,1610612740,0,12020,2020-12-21,West,New Orleans,2,2,0,1.00,1-0,1-0,NaN
3,1610612745,0,12020,2020-12-21,West,Houston,4,3,1,0.75,2-0,1-1,NaN
4,1610612763,0,12020,2020-12-21,West,Memphis,4,3,1,0.75,1-1,2-0,NaN

In [5]:
##Data Exploration

In [6]:
# #what is the win rate over the entire dataset for each team?

# # Total number of matches.
# n_matches = data.shape[0]

# # Calculate number of features. -1 because we are saving one as the target variable (win/lose/draw)
# n_features = data.shape[1] - 1

# # Calculate matches won by home team.
# n_homewins = len(data[data.FTR == 'H'])

# # Calculate win rate for home team.
# win_rate = (float(n_homewins) / (n_matches)) * 100

In [30]:
# df['DataFrame Column'] = df['DataFrame Column'].astype(str)
# df['DataFrame Column'] = df['DataFrame Column'].apply(str)
# d['Report Number'] = d['Report Number'].str[3:]

In [7]:
games_df

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,2020-12-19,12000047,Final,1610612753,1610612766,2020,1610612753,120.0,0.433,0.792,...,23.0,50.0,1610612766,117.0,0.444,0.864,0.439,21.0,52.0,1
1,2020-12-19,12000048,Final,1610612764,1610612765,2020,1610612764,99.0,0.427,0.625,...,24.0,45.0,1610612765,96.0,0.402,0.647,0.326,18.0,51.0,1
2,2020-12-19,12000049,Final,1610612763,1610612737,2020,1610612763,116.0,0.400,0.744,...,21.0,43.0,1610612737,117.0,0.422,0.837,0.297,24.0,47.0,0
3,2020-12-18,12000039,Final,1610612754,1610612755,2020,1610612754,107.0,0.371,0.692,...,19.0,45.0,1610612755,113.0,0.533,0.629,0.355,23.0,48.0,0
4,2020-12-18,12000040,Final,1610612761,1610612748,2020,1610612761,105.0,0.380,0.737,...,27.0,37.0,1610612748,117.0,0.534,0.741,0.514,30.0,51.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23515,2014-10-06,11400007,Final,1610612737,1610612740,2014,1610612737,93.0,0.419,0.821,...,24.0,50.0,1610612740,87.0,0.366,0.643,0.375,17.0,43.0,1
23516,2014-10-06,11400004,Final,1610612741,1610612764,2014,1610612741,81.0,0.338,0.719,...,18.0,40.0,1610612764,85.0,0.411,0.636,0.267,17.0,47.0,0
23517,2014-10-06,11400005,Final,1610612747,1610612743,2014,1610612747,98.0,0.448,0.682,...,29.0,45.0,1610612743,95.0,0.387,0.659,0.500,19.0,43.0,1
23518,2014-10-05,11400002,Final,1610612761,1610612758,2014,1610612761,99.0,0.440,0.771,...,21.0,30.0,1610612758,94.0,0.469,0.725,0.385,18.0,45.0,1
23519,2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,...,18.0,42.0,1610612740,98.0,0.462,0.706,0.438,19.0,42.0,0

In [31]:
ranking_df['SEASON_ID'] = ranking_df['SEASON_ID'].astype(str)
ranking_df['SEASON_ID'] = ranking_df['SEASON_ID'].str[1:]

In [10]:
ranking_df

,TEAM_ID,LEAGUE_ID,SEASON_ID,STANDINGSDATE,CONFERENCE,TEAM,G,W,L,W_PCT,HOME_RECORD,ROAD_RECORD,RETURNTOPLAY
0,1610612747,0,12020,2020-12-21,West,L.A. Lakers,4,4,0,1.000,2-0,2-0,NaN
1,1610612762,0,12020,2020-12-21,West,Utah,3,3,0,1.000,2-0,1-0,NaN
2,1610612740,0,12020,2020-12-21,West,New Orleans,2,2,0,1.000,1-0,1-0,NaN
3,1610612745,0,12020,2020-12-21,West,Houston,4,3,1,0.750,2-0,1-1,NaN
4,1610612763,0,12020,2020-12-21,West,Memphis,4,3,1,0.750,1-1,2-0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
188378,1610612765,0,22013,2014-09-01,East,Detroit,82,29,53,0.354,17-24,12-29,NaN
188379,1610612738,0,22013,2014-09-01,East,Boston,82,25,57,0.305,16-25,9-32,NaN
188380,1610612753,0,22013,2014-09-01,East,Orlando,82,23,59,0.280,19-22,4-37,NaN
188381,1610612755,0,22013,2014-09-01,East,Philadelphia,82,19,63,0.232,10-31,9-32,NaN
188382,1610612749,0,22013,2014-09-01,East,Milwaukee,82,15,67,0.183,10-31,5-36,NaN

In [11]:
len(ranking_df)

188383

In [12]:
games_df['SEASON_ID'] = games_df['SEASON_ID'].astype(str)

KeyError: 'SEASON_ID'

In [23]:
len(games_df)

23520

In [ ]:
new_df = merge_df.merge(games_df,ranking_df,how='left',left_on=,right_on)